"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"


def bool_env(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    return default if value is None else value.lower() == "true"


def int_env(name: str, default: int = 0) -> int:
    return int(os.getenv(name, str(default)))


def float_env(name: str, default: float = 0.0) -> float:
    return float(os.getenv(name, str(default)))


def csv_env(name: str, default: str = "") -> list[str]:
    return [
        value.strip() for value in os.getenv(name, default).split(",") if value.strip()
    ]


ALLOWED_HOSTS = csv_env("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")

# JWT session tokens (see docs/authentication.md). These tokens represent a
# short-lived, anonymous "trusted client" handshake, not a user account.
JWT_SIGNING_KEY = os.getenv("JWT_SIGNING_KEY") or SECRET_KEY
JWT_PREVIOUS_SIGNING_KEYS = csv_env("JWT_PREVIOUS_SIGNING_KEYS")
JWT_ACCESS_TOKEN_TTL_SECONDS = int_env("JWT_ACCESS_TOKEN_TTL_SECONDS", 300)
JWT_ISSUER = os.getenv("JWT_ISSUER", "yeshivish-translator")


# Shared cache (see docs/operations.md). Rate-limit counters, the JWT
# revocation denylist, and cost/usage guardrail counters all use Django's
# cache framework. `REDIS_URL` must be set in any multi-process/multi-instance
# deployment so these limits are enforced consistently across workers -
# otherwise each process gets its own independent, in-memory counters, which
# is only appropriate for local development and tests.
REDIS_URL = os.getenv("REDIS_URL")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
    if not DEBUG:
        import warnings

        warnings.warn(
            "REDIS_URL is not set and DJANGO_DEBUG is false. Falling back to "
            "an in-process cache means rate limits, the JWT revocation "
            "denylist, and cost guardrails are NOT shared across workers or "
            "instances. Set REDIS_URL before deploying with more than one "
            "process. See docs/operations.md.",
            RuntimeWarning,
            stacklevel=2,
        )

# Number of trusted reverse-proxy hops in front of this app (e.g. a load
# balancer or CDN). Determines how `X-Forwarded-For` is parsed for throttling
# and logging. Defaults to 0 (trust only `REMOTE_ADDR`, ignore
# `X-Forwarded-For` entirely) because that header is trivially spoofable by
# any direct caller unless a specific number of trusted hops is configured.
# See docs/operations.md for how to size this for your deployment.
TRUSTED_PROXY_COUNT = int_env("TRUSTED_PROXY_COUNT", 0)

# OpenAI request resilience (see docs/operations.md). Bounded so a slow or
# unresponsive upstream cannot hang a worker indefinitely or retry silently.
OPENAI_CONNECT_TIMEOUT_SECONDS = float_env("OPENAI_CONNECT_TIMEOUT_SECONDS", 5.0)
OPENAI_READ_TIMEOUT_SECONDS = float_env("OPENAI_READ_TIMEOUT_SECONDS", 20.0)
OPENAI_MAX_RETRIES = int_env("OPENAI_MAX_RETRIES", 1)

# Global cost/usage guardrails (see docs/operations.md). Once either budget is
# exceeded within the rolling window, `/api/translate/` stops calling OpenAI
# and returns a generic 503 until the window resets, regardless of individual
# throttle limits.
OPENAI_INPUT_COST_PER_MILLION_TOKENS = float_env(
    "OPENAI_INPUT_COST_PER_MILLION_TOKENS", 0.15
)
OPENAI_OUTPUT_COST_PER_MILLION_TOKENS = float_env(
    "OPENAI_OUTPUT_COST_PER_MILLION_TOKENS", 0.60
)
DAILY_COST_BUDGET_USD = float_env("DAILY_COST_BUDGET_USD", 20.0)
DAILY_REQUEST_BUDGET = int_env("DAILY_REQUEST_BUDGET", 5000)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "translator",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.DisableClientSideCompressionMiddleware",
]

CORS_ALLOWED_ORIGINS = csv_env("CORS_ALLOWED_ORIGINS", "http://localhost:5173")
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# HTTPS settings are opt-in for local development and must be enabled by the
# production environment after TLS termination has been configured.
SECURE_SSL_REDIRECT = bool_env("DJANGO_SECURE_SSL_REDIRECT")
SESSION_COOKIE_SECURE = bool_env("DJANGO_SESSION_COOKIE_SECURE")
CSRF_COOKIE_SECURE = bool_env("DJANGO_CSRF_COOKIE_SECURE")
SECURE_HSTS_SECONDS = int_env("DJANGO_SECURE_HSTS_SECONDS")
SECURE_HSTS_INCLUDE_SUBDOMAINS = bool_env("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS")
SECURE_HSTS_PRELOAD = bool_env("DJANGO_SECURE_HSTS_PRELOAD")

if bool_env("DJANGO_TRUST_X_FORWARDED_PROTO"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("THROTTLE_RATE_ANON", "60/hour"),
        # Per-IP limits.
        "auth_session": os.getenv("THROTTLE_RATE_AUTH_SESSION_IP", "30/hour"),
        "translate": os.getenv("THROTTLE_RATE_TRANSLATE_IP", "60/hour"),
        # Per-session-token limits (the "authenticated-user where applicable"
        # identity for this anonymous, tokenless-account app - see
        # docs/operations.md).
        "translate_session": os.getenv("THROTTLE_RATE_TRANSLATE_SESSION", "120/hour"),
        # Global limits shared by every caller, regardless of IP or session.
        "auth_session_global": os.getenv(
            "THROTTLE_RATE_AUTH_SESSION_GLOBAL", "600/hour"
        ),
        "translate_global": os.getenv("THROTTLE_RATE_TRANSLATE_GLOBAL", "2000/hour"),
    },
    "NUM_PROXIES": TRUSTED_PROXY_COUNT,
}

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
