# Generated by Django 5.2.17 on 2026-08-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True)),
                ('dialect_pattern', models.CharField(blank=True, max_length=200)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('meanings', models.JSONField(default=list)),
                ('context_note', models.TextField()),
                ('category', models.CharField(blank=True, max_length=120)),
                ('language_origin', models.CharField(blank=True, max_length=80)),
                ('yeshivish_example', models.TextField(blank=True)),
                ('plain_english_example', models.TextField(blank=True)),
                ('confidence', models.CharField(blank=True, max_length=40)),
                ('needs_human_review', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('term',),
            },
        ),
    ]
