# Generated by Django 5.2.17 on 2026-08-11 17:22

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_import_runtime_glossary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryterm',
            options={'ordering': (django.db.models.functions.text.Lower('term'),)},
        ),
    ]
